In [1]:
import torch
import numpy as np
import pandas as pd
import cv2 

In [ ]:
class NN:
    def __init__(self, data):
        self.data = data;
        self.grad = 0;  
    
    

In [2]:
img = cv2.imread("number-3.jpeg", 0)

cv2.imshow("hiii", img)

In [3]:
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
print(img)

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [19 19 51 ... 51 51 19]]


In [6]:
img.shape

(452, 451)